# Copyright 2026-present Orbit Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from orbit.plugins.v1 import process_plugin_pb2 as orbit_dot_plugins_dot_v1_dot_process__plugin__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in orbit/plugins/v1/process_plugin_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProcessPluginStub:
    """Core and a supervised local plugin exchange lifecycle frames on one stream.
    Capability packages define their own typed services in separately installable repos.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connect = channel.stream_stream(
                '/orbit.plugin.v1.ProcessPlugin/Connect',
                request_serializer=orbit_dot_plugins_dot_v1_dot_process__plugin__pb2.PluginFrame.SerializeToString,
                response_deserializer=orbit_dot_plugins_dot_v1_dot_process__plugin__pb2.CoreFrame.FromString,
                _registered_method=True)


class ProcessPluginServicer:
    """Core and a supervised local plugin exchange lifecycle frames on one stream.
    Capability packages define their own typed services in separately installable repos.
    """

    def Connect(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProcessPluginServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Connect': grpc.stream_stream_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=orbit_dot_plugins_dot_v1_dot_process__plugin__pb2.PluginFrame.FromString,
                    response_serializer=orbit_dot_plugins_dot_v1_dot_process__plugin__pb2.CoreFrame.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'orbit.plugin.v1.ProcessPlugin', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('orbit.plugin.v1.ProcessPlugin', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProcessPlugin:
    """Core and a supervised local plugin exchange lifecycle frames on one stream.
    Capability packages define their own typed services in separately installable repos.
    """

    @staticmethod
    def Connect(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/orbit.plugin.v1.ProcessPlugin/Connect',
            orbit_dot_plugins_dot_v1_dot_process__plugin__pb2.PluginFrame.SerializeToString,
            orbit_dot_plugins_dot_v1_dot_process__plugin__pb2.CoreFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
