"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2026-present Orbit Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

import builtins
import collections.abc
import google.protobuf.any_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class PluginMetadata(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    API_VERSION_FIELD_NUMBER: builtins.int
    DEPENDENCIES_FIELD_NUMBER: builtins.int
    OPTIONAL_DEPENDENCIES_FIELD_NUMBER: builtins.int
    CAPABILITIES_FIELD_NUMBER: builtins.int
    REQUIRED_CAPABILITIES_FIELD_NUMBER: builtins.int
    id: builtins.str
    name: builtins.str
    version: builtins.str
    api_version: builtins.str
    @property
    def dependencies(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def optional_dependencies(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def capabilities(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def required_capabilities(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        name: builtins.str = ...,
        version: builtins.str = ...,
        api_version: builtins.str = ...,
        dependencies: collections.abc.Iterable[builtins.str] | None = ...,
        optional_dependencies: collections.abc.Iterable[builtins.str] | None = ...,
        capabilities: collections.abc.Iterable[builtins.str] | None = ...,
        required_capabilities: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["api_version", b"api_version", "capabilities", b"capabilities", "dependencies", b"dependencies", "id", b"id", "name", b"name", "optional_dependencies", b"optional_dependencies", "required_capabilities", b"required_capabilities", "version", b"version"]) -> None: ...

Global___PluginMetadata: typing_extensions.TypeAlias = PluginMetadata

@typing.final
class PluginFrame(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HELLO_FIELD_NUMBER: builtins.int
    COMMAND_RESULT_FIELD_NUMBER: builtins.int
    HEALTH_FIELD_NUMBER: builtins.int
    CAPABILITY_RESULT_FIELD_NUMBER: builtins.int
    @property
    def hello(self) -> Global___PluginHello: ...
    @property
    def command_result(self) -> Global___CommandResult: ...
    @property
    def health(self) -> Global___PluginHealth: ...
    @property
    def capability_result(self) -> Global___CapabilityResult: ...
    def __init__(
        self,
        *,
        hello: Global___PluginHello | None = ...,
        command_result: Global___CommandResult | None = ...,
        health: Global___PluginHealth | None = ...,
        capability_result: Global___CapabilityResult | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["capability_result", b"capability_result", "command_result", b"command_result", "health", b"health", "hello", b"hello", "payload", b"payload"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["capability_result", b"capability_result", "command_result", b"command_result", "health", b"health", "hello", b"hello", "payload", b"payload"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["payload", b"payload"]) -> typing.Literal["hello", "command_result", "health", "capability_result"] | None: ...

Global___PluginFrame: typing_extensions.TypeAlias = PluginFrame

@typing.final
class PluginHello(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROTOCOL_MAJOR_FIELD_NUMBER: builtins.int
    PROTOCOL_MINOR_FIELD_NUMBER: builtins.int
    METADATA_FIELD_NUMBER: builtins.int
    protocol_major: builtins.int
    protocol_minor: builtins.int
    @property
    def metadata(self) -> Global___PluginMetadata: ...
    def __init__(
        self,
        *,
        protocol_major: builtins.int = ...,
        protocol_minor: builtins.int = ...,
        metadata: Global___PluginMetadata | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["metadata", b"metadata"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["metadata", b"metadata", "protocol_major", b"protocol_major", "protocol_minor", b"protocol_minor"]) -> None: ...

Global___PluginHello: typing_extensions.TypeAlias = PluginHello

@typing.final
class CommandResult(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REQUEST_ID_FIELD_NUMBER: builtins.int
    SUCCEEDED_FIELD_NUMBER: builtins.int
    ERROR_CODE_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    request_id: builtins.int
    succeeded: builtins.bool
    error_code: builtins.str
    error_message: builtins.str
    def __init__(
        self,
        *,
        request_id: builtins.int = ...,
        succeeded: builtins.bool = ...,
        error_code: builtins.str = ...,
        error_message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["error_code", b"error_code", "error_message", b"error_message", "request_id", b"request_id", "succeeded", b"succeeded"]) -> None: ...

Global___CommandResult: typing_extensions.TypeAlias = CommandResult

@typing.final
class CapabilityResult(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REQUEST_ID_FIELD_NUMBER: builtins.int
    RESPONSE_FIELD_NUMBER: builtins.int
    ERROR_CODE_FIELD_NUMBER: builtins.int
    request_id: builtins.int
    error_code: builtins.str
    @property
    def response(self) -> google.protobuf.any_pb2.Any: ...
    def __init__(
        self,
        *,
        request_id: builtins.int = ...,
        response: google.protobuf.any_pb2.Any | None = ...,
        error_code: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["response", b"response"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["error_code", b"error_code", "request_id", b"request_id", "response", b"response"]) -> None: ...

Global___CapabilityResult: typing_extensions.TypeAlias = CapabilityResult

@typing.final
class PluginHealth(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Status:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _StatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[PluginHealth._Status.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        STATUS_UNSPECIFIED: PluginHealth._Status.ValueType  # 0
        STATUS_HEALTHY: PluginHealth._Status.ValueType  # 1
        STATUS_DEGRADED: PluginHealth._Status.ValueType  # 2
        STATUS_UNHEALTHY: PluginHealth._Status.ValueType  # 3

    class Status(_Status, metaclass=_StatusEnumTypeWrapper): ...
    STATUS_UNSPECIFIED: PluginHealth.Status.ValueType  # 0
    STATUS_HEALTHY: PluginHealth.Status.ValueType  # 1
    STATUS_DEGRADED: PluginHealth.Status.ValueType  # 2
    STATUS_UNHEALTHY: PluginHealth.Status.ValueType  # 3

    REQUEST_ID_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    request_id: builtins.int
    status: Global___PluginHealth.Status.ValueType
    message: builtins.str
    def __init__(
        self,
        *,
        request_id: builtins.int = ...,
        status: Global___PluginHealth.Status.ValueType = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["message", b"message", "request_id", b"request_id", "status", b"status"]) -> None: ...

Global___PluginHealth: typing_extensions.TypeAlias = PluginHealth

@typing.final
class CoreFrame(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    COMMAND_FIELD_NUMBER: builtins.int
    HEALTH_PROBE_FIELD_NUMBER: builtins.int
    SHUTDOWN_FIELD_NUMBER: builtins.int
    CAPABILITY_CALL_FIELD_NUMBER: builtins.int
    @property
    def command(self) -> Global___PluginCommand: ...
    @property
    def health_probe(self) -> Global___HealthProbe: ...
    @property
    def shutdown(self) -> Global___Shutdown: ...
    @property
    def capability_call(self) -> Global___CapabilityCall: ...
    def __init__(
        self,
        *,
        command: Global___PluginCommand | None = ...,
        health_probe: Global___HealthProbe | None = ...,
        shutdown: Global___Shutdown | None = ...,
        capability_call: Global___CapabilityCall | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["capability_call", b"capability_call", "command", b"command", "health_probe", b"health_probe", "payload", b"payload", "shutdown", b"shutdown"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["capability_call", b"capability_call", "command", b"command", "health_probe", b"health_probe", "payload", b"payload", "shutdown", b"shutdown"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["payload", b"payload"]) -> typing.Literal["command", "health_probe", "shutdown", "capability_call"] | None: ...

Global___CoreFrame: typing_extensions.TypeAlias = CoreFrame

@typing.final
class PluginCommand(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Kind:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _KindEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[PluginCommand._Kind.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        KIND_UNSPECIFIED: PluginCommand._Kind.ValueType  # 0
        KIND_ACTIVATE: PluginCommand._Kind.ValueType  # 1
        KIND_DEACTIVATE: PluginCommand._Kind.ValueType  # 2

    class Kind(_Kind, metaclass=_KindEnumTypeWrapper): ...
    KIND_UNSPECIFIED: PluginCommand.Kind.ValueType  # 0
    KIND_ACTIVATE: PluginCommand.Kind.ValueType  # 1
    KIND_DEACTIVATE: PluginCommand.Kind.ValueType  # 2

    REQUEST_ID_FIELD_NUMBER: builtins.int
    KIND_FIELD_NUMBER: builtins.int
    CONFIGURATION_JSON_FIELD_NUMBER: builtins.int
    request_id: builtins.int
    kind: Global___PluginCommand.Kind.ValueType
    configuration_json: builtins.bytes
    def __init__(
        self,
        *,
        request_id: builtins.int = ...,
        kind: Global___PluginCommand.Kind.ValueType = ...,
        configuration_json: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["configuration_json", b"configuration_json", "kind", b"kind", "request_id", b"request_id"]) -> None: ...

Global___PluginCommand: typing_extensions.TypeAlias = PluginCommand

@typing.final
class HealthProbe(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REQUEST_ID_FIELD_NUMBER: builtins.int
    request_id: builtins.int
    def __init__(
        self,
        *,
        request_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["request_id", b"request_id"]) -> None: ...

Global___HealthProbe: typing_extensions.TypeAlias = HealthProbe

@typing.final
class CapabilityCall(google.protobuf.message.Message):
    """Capability packages publish their typed request/response messages in their own repositories."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REQUEST_ID_FIELD_NUMBER: builtins.int
    METHOD_FIELD_NUMBER: builtins.int
    REQUEST_FIELD_NUMBER: builtins.int
    request_id: builtins.int
    method: builtins.str
    @property
    def request(self) -> google.protobuf.any_pb2.Any: ...
    def __init__(
        self,
        *,
        request_id: builtins.int = ...,
        method: builtins.str = ...,
        request: google.protobuf.any_pb2.Any | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["request", b"request"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["method", b"method", "request", b"request", "request_id", b"request_id"]) -> None: ...

Global___CapabilityCall: typing_extensions.TypeAlias = CapabilityCall

@typing.final
class Shutdown(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___Shutdown: typing_extensions.TypeAlias = Shutdown
