"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2026-present Orbit Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

import abc
import collections.abc
import grpc
import grpc.aio
import orbit.plugins.v1.process_plugin_pb2
import sys
import typing

if sys.version_info >= (3, 13):
    import typing as typing_extensions
else:
    import typing_extensions

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str
_ProcessPluginConnectType = typing_extensions.TypeVar(
    '_ProcessPluginConnectType',
    grpc.StreamStreamMultiCallable[
        orbit.plugins.v1.process_plugin_pb2.PluginFrame,
        orbit.plugins.v1.process_plugin_pb2.CoreFrame,
    ],
    grpc.aio.StreamStreamMultiCallable[
        orbit.plugins.v1.process_plugin_pb2.PluginFrame,
        orbit.plugins.v1.process_plugin_pb2.CoreFrame,
    ],
    default=grpc.StreamStreamMultiCallable[
        orbit.plugins.v1.process_plugin_pb2.PluginFrame,
        orbit.plugins.v1.process_plugin_pb2.CoreFrame,
    ],
)

class ProcessPluginStub(typing.Generic[_ProcessPluginConnectType]):
    """Core and a supervised local plugin exchange lifecycle frames on one stream.
    Capability packages define their own typed services in separately installable repos.
    """

    @typing.overload
    def __init__(self: ProcessPluginStub[
        grpc.StreamStreamMultiCallable[
            orbit.plugins.v1.process_plugin_pb2.PluginFrame,
            orbit.plugins.v1.process_plugin_pb2.CoreFrame,
        ],
    ], channel: grpc.Channel) -> None: ...

    @typing.overload
    def __init__(self: ProcessPluginStub[
        grpc.aio.StreamStreamMultiCallable[
            orbit.plugins.v1.process_plugin_pb2.PluginFrame,
            orbit.plugins.v1.process_plugin_pb2.CoreFrame,
        ],
    ], channel: grpc.aio.Channel) -> None: ...

    Connect: _ProcessPluginConnectType

ProcessPluginAsyncStub: typing_extensions.TypeAlias = ProcessPluginStub[
    grpc.aio.StreamStreamMultiCallable[
        orbit.plugins.v1.process_plugin_pb2.PluginFrame,
        orbit.plugins.v1.process_plugin_pb2.CoreFrame,
    ],
]

class ProcessPluginServicer(metaclass=abc.ABCMeta):
    """Core and a supervised local plugin exchange lifecycle frames on one stream.
    Capability packages define their own typed services in separately installable repos.
    """

    @abc.abstractmethod
    def Connect(
        self,
        request_iterator: _MaybeAsyncIterator[orbit.plugins.v1.process_plugin_pb2.PluginFrame],
        context: _ServicerContext,
    ) -> typing.Union[collections.abc.Iterator[orbit.plugins.v1.process_plugin_pb2.CoreFrame], collections.abc.AsyncIterator[orbit.plugins.v1.process_plugin_pb2.CoreFrame]]: ...

def add_ProcessPluginServicer_to_server(servicer: ProcessPluginServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
